//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.CmsKit.ContentDefinitions.Dtos
{
    public partial class ContentTypePartDefinitionAutoMapperProfile : Profile
    {
        public ContentTypePartDefinitionAutoMapperProfile()
        {
            CreateMap<FS.CmsKit.ContentDefinitions.ContentTypePartDefinition, ContentTypePartDefinitionDto>()
            .ReverseMap();
        
            CreateMap<ContentTypePartDefinitionCreateDto, FS.CmsKit.ContentDefinitions.ContentTypePartDefinition>();
        
            CreateMap<ContentTypePartDefinitionUpdateDto, FS.CmsKit.ContentDefinitions.ContentTypePartDefinition>();
        
            CreateMap<FS.CmsKit.ContentDefinitions.ContentTypePartDefinition, ContentTypePartDefinitionWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
