////------------------------------------------------------------------------------
//// This is auto-generated code.
////------------------------------------------------------------------------------
//// This code was generated by YinChang.
//// 5.1.3
////
//// Changes to this file may cause incorrect behavior and will be lost if
//// the code is regenerated.
////------------------------------------------------------------------------------
//using System.Reflection;
//using AutoMapper;
//using Volo.Abp.AutoMapper;

//namespace FS.CmsKit.ContentDefinitions.Dtos
//{
//    public partial class ContentTypeDefinitionAutoMapperProfile : Profile
//    {
//        partial void CustomizeConfiguration()
//        {
//            CreateMap<FS.CmsKit.ContentDefinitions.ContentTypeDefinition, V1.ContentTypeDefinitionWithDetailsDto>();
//        }
//    }

//}
