//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
using FS.Entity.EntityDefaults.EntityFrameworkCore;
using FS.Entity.MultiLinguals.EntityFrameworkCore;


namespace FS.EntityManagement.EntityFrameworkCore
{
    public static partial class EntityManagementDbContextModelCreatingExtensions
    {
        public static void ConfigureEntityManagement(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ConfigureEntityDefaults();
            builder.ConfigureMultiLinguals();

        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
