//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Social.Codes
{
    public partial interface ICodeCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.Social.Codes.Dtos.CodeWithDetailsDto, 
            FS.Social.Codes.Dtos.CodeDto, 
            Guid, 
            FS.Social.Codes.Dtos.CodeGetListDto, 
            FS.Social.Codes.Dtos.CodeCreateDto, 
            FS.Social.Codes.Dtos.CodeUpdateDto>
    {

    }
}
