//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.CmsKit.ContentComposites.Permissions
{
    public class ContentCompositesPermissionNames
    {
        public const string ModuleName = "FS.CmsKit.ContentComposites";
        public static class ContentItem
        {
            public const string Default = ModuleName + ".ContentItem";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ContentComposite
        {
            public const string Default = ModuleName + ".ContentComposite";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ImageComposite
        {
            public const string Default = ModuleName + ".ImageComposite";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class AttachmentComposite
        {
            public const string Default = ModuleName + ".AttachmentComposite";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ContentComponent
        {
            public const string Default = ModuleName + ".ContentComponent";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(ContentCompositesPermissionNames));
        }
    }
}
