//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.CmsKit.Localization;
using FS.CmsKit.Permissions;

namespace FS.CmsKit.ContentComposites.Permissions
{
    public partial class ContentCompositesPermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var group = context.GetGroup(CmsKitPermissions.GroupName);

            var ContentItem = group.AddPermission(ContentCompositesPermissionNames.ContentItem.Default,L(ContentCompositesPermissionNames.ContentItem.Default));
            ContentItem.AddChild(ContentCompositesPermissionNames.ContentItem.Create , L("DisplayName:ContentItem.Create"));
            ContentItem.AddChild(ContentCompositesPermissionNames.ContentItem.Update , L("DisplayName:ContentItem.Update"));
            ContentItem.AddChild(ContentCompositesPermissionNames.ContentItem.Delete , L("DisplayName:ContentItem.Delete"));

            var ContentComposite = group.AddPermission(ContentCompositesPermissionNames.ContentComposite.Default,L(ContentCompositesPermissionNames.ContentComposite.Default));
            ContentComposite.AddChild(ContentCompositesPermissionNames.ContentComposite.Create , L("DisplayName:ContentComposite.Create"));
            ContentComposite.AddChild(ContentCompositesPermissionNames.ContentComposite.Update , L("DisplayName:ContentComposite.Update"));
            ContentComposite.AddChild(ContentCompositesPermissionNames.ContentComposite.Delete , L("DisplayName:ContentComposite.Delete"));

            var ImageComposite = group.AddPermission(ContentCompositesPermissionNames.ImageComposite.Default,L(ContentCompositesPermissionNames.ImageComposite.Default));
            ImageComposite.AddChild(ContentCompositesPermissionNames.ImageComposite.Create , L("DisplayName:ImageComposite.Create"));
            ImageComposite.AddChild(ContentCompositesPermissionNames.ImageComposite.Update , L("DisplayName:ImageComposite.Update"));
            ImageComposite.AddChild(ContentCompositesPermissionNames.ImageComposite.Delete , L("DisplayName:ImageComposite.Delete"));

            var AttachmentComposite = group.AddPermission(ContentCompositesPermissionNames.AttachmentComposite.Default,L(ContentCompositesPermissionNames.AttachmentComposite.Default));
            AttachmentComposite.AddChild(ContentCompositesPermissionNames.AttachmentComposite.Create , L("DisplayName:AttachmentComposite.Create"));
            AttachmentComposite.AddChild(ContentCompositesPermissionNames.AttachmentComposite.Update , L("DisplayName:AttachmentComposite.Update"));
            AttachmentComposite.AddChild(ContentCompositesPermissionNames.AttachmentComposite.Delete , L("DisplayName:AttachmentComposite.Delete"));

            var ContentComponent = group.AddPermission(ContentCompositesPermissionNames.ContentComponent.Default,L(ContentCompositesPermissionNames.ContentComponent.Default));
            ContentComponent.AddChild(ContentCompositesPermissionNames.ContentComponent.Create , L("DisplayName:ContentComponent.Create"));
            ContentComponent.AddChild(ContentCompositesPermissionNames.ContentComponent.Update , L("DisplayName:ContentComponent.Update"));
            ContentComponent.AddChild(ContentCompositesPermissionNames.ContentComponent.Delete , L("DisplayName:ContentComponent.Delete"));

            CustomizeDefine(context);
        }

        partial void CustomizeDefine(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context);

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<CmsKitResource>(name);
        }
    }
}
