//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.CmsKit.Localization;
using FS.CmsKit.Permissions;

namespace FS.CmsKit.ContentDefinitions.Permissions
{
    public partial class ContentDefinitionsPermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var group = context.GetGroup(CmsKitPermissions.GroupName);

            var ContentTypeDefinition = group.AddPermission(ContentDefinitionsPermissionNames.ContentTypeDefinition.Default,L(ContentDefinitionsPermissionNames.ContentTypeDefinition.Default));
            ContentTypeDefinition.AddChild(ContentDefinitionsPermissionNames.ContentTypeDefinition.Create , L("DisplayName:ContentTypeDefinition.Create"));
            ContentTypeDefinition.AddChild(ContentDefinitionsPermissionNames.ContentTypeDefinition.Update , L("DisplayName:ContentTypeDefinition.Update"));
            ContentTypeDefinition.AddChild(ContentDefinitionsPermissionNames.ContentTypeDefinition.Delete , L("DisplayName:ContentTypeDefinition.Delete"));

            var ContentTypePartDefinition = group.AddPermission(ContentDefinitionsPermissionNames.ContentTypePartDefinition.Default,L(ContentDefinitionsPermissionNames.ContentTypePartDefinition.Default));
            ContentTypePartDefinition.AddChild(ContentDefinitionsPermissionNames.ContentTypePartDefinition.Create , L("DisplayName:ContentTypePartDefinition.Create"));
            ContentTypePartDefinition.AddChild(ContentDefinitionsPermissionNames.ContentTypePartDefinition.Update , L("DisplayName:ContentTypePartDefinition.Update"));
            ContentTypePartDefinition.AddChild(ContentDefinitionsPermissionNames.ContentTypePartDefinition.Delete , L("DisplayName:ContentTypePartDefinition.Delete"));

            var ContentPartDefinition = group.AddPermission(ContentDefinitionsPermissionNames.ContentPartDefinition.Default,L(ContentDefinitionsPermissionNames.ContentPartDefinition.Default));
            ContentPartDefinition.AddChild(ContentDefinitionsPermissionNames.ContentPartDefinition.Create , L("DisplayName:ContentPartDefinition.Create"));
            ContentPartDefinition.AddChild(ContentDefinitionsPermissionNames.ContentPartDefinition.Update , L("DisplayName:ContentPartDefinition.Update"));
            ContentPartDefinition.AddChild(ContentDefinitionsPermissionNames.ContentPartDefinition.Delete , L("DisplayName:ContentPartDefinition.Delete"));

            var ContentPartFieldDefinition = group.AddPermission(ContentDefinitionsPermissionNames.ContentPartFieldDefinition.Default,L(ContentDefinitionsPermissionNames.ContentPartFieldDefinition.Default));
            ContentPartFieldDefinition.AddChild(ContentDefinitionsPermissionNames.ContentPartFieldDefinition.Create , L("DisplayName:ContentPartFieldDefinition.Create"));
            ContentPartFieldDefinition.AddChild(ContentDefinitionsPermissionNames.ContentPartFieldDefinition.Update , L("DisplayName:ContentPartFieldDefinition.Update"));
            ContentPartFieldDefinition.AddChild(ContentDefinitionsPermissionNames.ContentPartFieldDefinition.Delete , L("DisplayName:ContentPartFieldDefinition.Delete"));

            var ContentDefinition = group.AddPermission(ContentDefinitionsPermissionNames.ContentDefinition.Default,L(ContentDefinitionsPermissionNames.ContentDefinition.Default));
            ContentDefinition.AddChild(ContentDefinitionsPermissionNames.ContentDefinition.Create , L("DisplayName:ContentDefinition.Create"));
            ContentDefinition.AddChild(ContentDefinitionsPermissionNames.ContentDefinition.Update , L("DisplayName:ContentDefinition.Update"));
            ContentDefinition.AddChild(ContentDefinitionsPermissionNames.ContentDefinition.Delete , L("DisplayName:ContentDefinition.Delete"));

            CustomizeDefine(context);
        }

        partial void CustomizeDefine(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context);

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<CmsKitResource>(name);
        }
    }
}
