//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.CmsKit.ContentDefinitions.Permissions
{
    public class ContentDefinitionsPermissionNames
    {
        public const string ModuleName = "FS.CmsKit.ContentDefinitions";
        public static class ContentTypeDefinition
        {
            public const string Default = ModuleName + ".ContentTypeDefinition";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ContentTypePartDefinition
        {
            public const string Default = ModuleName + ".ContentTypePartDefinition";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ContentPartDefinition
        {
            public const string Default = ModuleName + ".ContentPartDefinition";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ContentPartFieldDefinition
        {
            public const string Default = ModuleName + ".ContentPartFieldDefinition";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ContentDefinition
        {
            public const string Default = ModuleName + ".ContentDefinition";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(ContentDefinitionsPermissionNames));
        }
    }
}
