//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.Abp.Emailing.Dtos
{
    public partial class MailMessageTemplateCreateDtoValidator : AbstractValidator<MailMessageTemplateCreateDto>
    {
        public MailMessageTemplateCreateDtoValidator()
        {
            RuleFor(p => p.Title)
                .NotNull()
                ;
            RuleFor(p => p.No)
                .NotNull()
                ;
            RuleFor(p => p.DisplayName)
                .NotNull()
                ;
            RuleFor(p => p.CacheKey)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class MailMessageTemplateUpdateDtoValidator : AbstractValidator<MailMessageTemplateUpdateDto>
    {
        public MailMessageTemplateUpdateDtoValidator()
        {
            RuleFor(p => p.Title)
                .NotNull()
                ;
            RuleFor(p => p.No)
                .NotNull()
                ;
            RuleFor(p => p.DisplayName)
                .NotNull()
                ;
            RuleFor(p => p.CacheKey)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
