//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.Abp.Emailing.Dtos
{

    public partial class MailMessageTemplateDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string Title { get; set; }

        public virtual string No { get; set; }

        public virtual string DisplayName { get; set; }

        public virtual string CacheKey { get; set; }

    }

    public partial class MailMessageTemplateCreateDto
    {
        public virtual string Title { get; set; }

        public virtual string No { get; set; }

        public virtual string DisplayName { get; set; }

        public virtual string CacheKey { get; set; }

    }

    public partial class MailMessageTemplateUpdateDto
    {
        public virtual string Title { get; set; }

        public virtual string No { get; set; }

        public virtual string DisplayName { get; set; }

        public virtual string CacheKey { get; set; }

    }

    public partial class MailMessageTemplateGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class MailMessageTemplateWithDetailsDto : MailMessageTemplateDto
    {
    }
}
