//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.CmsKit.ContentEntities.Dtos
{
    public partial class ContentEntityAutoMapperProfile : Profile
    {
        public ContentEntityAutoMapperProfile()
        {
            CreateMap<FS.CmsKit.ContentEntities.ContentEntity, ContentEntityDto>()
            .ReverseMap();
        
            CreateMap<ContentEntityCreateDto, FS.CmsKit.ContentEntities.ContentEntity>();
        
            CreateMap<ContentEntityUpdateDto, FS.CmsKit.ContentEntities.ContentEntity>();
        
            CreateMap<FS.CmsKit.ContentEntities.ContentEntity, ContentEntityWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
