//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.CmsKit.ContentEntities.Permissions
{
    public class ContentEntitiesPermissionNames
    {
        public const string ModuleName = "FS.CmsKit.ContentEntities";
        public static class ContentEntity
        {
            public const string Default = ModuleName + ".ContentEntity";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(ContentEntitiesPermissionNames));
        }
    }
}
