//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.ContentComposites.Dtos
{

    public partial class AttachmentCompositeDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentDto
    {
        public virtual string LimitFileType { get; set; }

        public virtual string LimitFileSize { get; set; }

    }

    public partial class AttachmentCompositeCreateDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentCreateDto
    {
        public virtual string LimitFileType { get; set; }

        public virtual string LimitFileSize { get; set; }

    }

    public partial class AttachmentCompositeUpdateDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentUpdateDto
    {
        public virtual string LimitFileType { get; set; }

        public virtual string LimitFileSize { get; set; }

    }

    public partial class AttachmentCompositeGetListDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentGetListDto
    {
    }

    public partial class AttachmentCompositeWithDetailsDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentWithDetailsDto
    {
        public virtual string LimitFileType { get; set; }

        public virtual string LimitFileSize { get; set; }

    }
}
