//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.CmsKit.ContentComposites.Dtos
{
    public partial class ContentItemCreateDtoValidator : AbstractValidator<ContentItemCreateDto>
    {
        public ContentItemCreateDtoValidator()
        {
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class ContentItemUpdateDtoValidator : AbstractValidator<ContentItemUpdateDto>
    {
        public ContentItemUpdateDtoValidator()
        {
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
