//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.ContentComposites.Dtos
{

    public partial class ContentItemDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentDto
    {
    }

    public partial class ContentItemCreateDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentCreateDto
    {
    }

    public partial class ContentItemUpdateDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentUpdateDto
    {
    }

    public partial class ContentItemGetListDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentGetListDto
    {
    }

    public partial class ContentItemWithDetailsDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentWithDetailsDto
    {
    }
}
