//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.ContentComposites.Dtos
{

    public partial class ContentCompositeDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentDto
    {
    }

    public partial class ContentCompositeCreateDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentCreateDto
    {
    }

    public partial class ContentCompositeUpdateDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentUpdateDto
    {
    }

    public partial class ContentCompositeGetListDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentGetListDto
    {
    }

    public partial class ContentCompositeWithDetailsDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentWithDetailsDto
    {
    }
}
