//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.CmsKit.ContentComposites.Dtos
{
    public partial class ContentComponentCreateDtoValidator : AbstractValidator<ContentComponentCreateDto>
    {
        public ContentComponentCreateDtoValidator()
        {
            RuleFor(p => p.ContentEntityId)
                ;
            RuleFor(p => p.Code)
                .NotNull()
                ;
            RuleFor(p => p.ParentId)
                ;
            RuleFor(p => p.Level)
                ;
            RuleFor(p => p.DisplayName)
                .NotNull()
                ;
            RuleFor(p => p.ContentComponentDiscriminator)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class ContentComponentUpdateDtoValidator : AbstractValidator<ContentComponentUpdateDto>
    {
        public ContentComponentUpdateDtoValidator()
        {
            RuleFor(p => p.ContentEntityId)
                ;
            RuleFor(p => p.Code)
                .NotNull()
                ;
            RuleFor(p => p.ParentId)
                ;
            RuleFor(p => p.Level)
                ;
            RuleFor(p => p.DisplayName)
                .NotNull()
                ;
            RuleFor(p => p.ContentComponentDiscriminator)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
