//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace FS.CmsKit.ContentComposites.Dtos
{
    public partial class ContentItemJsonSubtypesConverterProfile : FS.Abp.JsonSubTypes.JsonSubtypesConverterProfile
    {
        public ContentItemJsonSubtypesConverterProfile()
        {
            this.CreateJsonSubtypesConverter<ContentComponentDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ContentItemDto>("ContentItem")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentCreateDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ContentItemCreateDto>("ContentItem")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentUpdateDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ContentItemUpdateDto>("ContentItem")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentGetListDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ContentItemGetListDto>("ContentItem")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentWithDetailsDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ContentItemWithDetailsDto>("ContentItem")
                ;

        }
    }

}
