//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace FS.CmsKit.ContentComposites.Dtos
{
    public partial class ContentCompositeJsonSubtypesConverterProfile : FS.Abp.JsonSubTypes.JsonSubtypesConverterProfile
    {
        public ContentCompositeJsonSubtypesConverterProfile()
        {
            this.CreateJsonSubtypesConverter<ContentComponentDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ContentCompositeDto>("ContentComposite")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentCreateDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ContentCompositeCreateDto>("ContentComposite")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentUpdateDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ContentCompositeUpdateDto>("ContentComposite")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentGetListDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ContentCompositeGetListDto>("ContentComposite")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentWithDetailsDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ContentCompositeWithDetailsDto>("ContentComposite")
                ;

        }
    }

}
