//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.ContentComposites.Dtos
{

    public partial class ImageCompositeDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentDto
    {
        public virtual string Width { get; set; }

        public virtual string Height { get; set; }

    }

    public partial class ImageCompositeCreateDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentCreateDto
    {
        public virtual string Width { get; set; }

        public virtual string Height { get; set; }

    }

    public partial class ImageCompositeUpdateDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentUpdateDto
    {
        public virtual string Width { get; set; }

        public virtual string Height { get; set; }

    }

    public partial class ImageCompositeGetListDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentGetListDto
    {
    }

    public partial class ImageCompositeWithDetailsDto : FS.CmsKit.ContentComposites.Dtos.ContentComponentWithDetailsDto
    {
        public virtual string Width { get; set; }

        public virtual string Height { get; set; }

    }
}
