//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

namespace FS.CmsKit.ContentComposites.Dtos
{
    public partial class ImageCompositeJsonSubtypesConverterProfile : FS.Abp.JsonSubTypes.JsonSubtypesConverterProfile
    {
        public ImageCompositeJsonSubtypesConverterProfile()
        {
            this.CreateJsonSubtypesConverter<ContentComponentDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ImageCompositeDto>("ImageComposite")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentCreateDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ImageCompositeCreateDto>("ImageComposite")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentUpdateDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ImageCompositeUpdateDto>("ImageComposite")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentGetListDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ImageCompositeGetListDto>("ImageComposite")
                ;

            this.CreateJsonSubtypesConverter<ContentComponentWithDetailsDto>("ContentComponentDiscriminator")
                .RegisterSubtype<FS.CmsKit.ContentComposites.Dtos.ImageCompositeWithDetailsDto>("ImageComposite")
                ;

        }
    }

}
