//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System.Reflection;
using System.Data.Common;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Volo.Abp.Data;
using Volo.Abp.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Volo.Abp.DependencyInjection;

namespace FS.CmsKitManagement.EntityFrameworkCore
{
    [ReplaceDbContext(typeof(FS.CmsKitManagement.Attachments.EntityFrameworkCore.IAttachmentsDbContext))]
    [ReplaceDbContext(typeof(FS.CmsKit.ContentDefinitions.EntityFrameworkCore.IContentDefinitionsDbContext))]
    [ReplaceDbContext(typeof(FS.CmsKitManagement.ContentRecords.EntityFrameworkCore.IContentRecordsDbContext))]
    [ReplaceDbContext(typeof(FS.CmsKit.ContentEntities.EntityFrameworkCore.IContentEntitiesDbContext))]
    [ReplaceDbContext(typeof(FS.CmsKit.ContentComposites.EntityFrameworkCore.IContentCompositesDbContext))]
    [ReplaceDbContext(typeof(FS.CmsKit.EntityMedias.EntityFrameworkCore.IEntityMediasDbContext))]
    [ConnectionStringName(CmsKitManagementDbProperties.ConnectionStringName)]
    public partial class CmsKitManagementDbContext : AbpDbContext<CmsKitManagementDbContext>, ICmsKitManagementDbContext
    {

        public virtual DbSet<FS.CmsKitManagement.Attachments.Attachment> Attachments
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentDefinitions.ContentTypeDefinition> ContentTypeDefinitions
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentDefinitions.ContentTypePartDefinition> ContentTypePartDefinitions
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentDefinitions.ContentPartDefinition> ContentPartDefinitions
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentDefinitions.ContentPartFieldDefinition> ContentPartFieldDefinitions
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentDefinitions.ContentDefinition> ContentDefinitions
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKitManagement.ContentRecords.ContentTypeRecord> ContentTypeRecords
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKitManagement.ContentRecords.ContentPartFieldRecord> ContentPartFieldRecords
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKitManagement.ContentRecords.ContentPartRecord> ContentPartRecords
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentEntities.ContentEntity> ContentEntities
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentComposites.ContentItem> ContentItems
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentComposites.ContentComposite> ContentComposites
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentComposites.ImageComposite> ImageComposites
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentComposites.AttachmentComposite> AttachmentComposites
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.ContentComposites.ContentComponent> ContentComponents
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.EntityMedias.EntityMedia> EntityMedia
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.EntityMedias.EntityMediaGroup> EntityMediaGroups
        {
            get;
            set;
        }

        public virtual DbSet<FS.CmsKit.EntityMedias.EntityMediaItem> EntityMediaItems
        {
            get;
            set;
        }
        public CmsKitManagementDbContext(DbContextOptions<CmsKitManagementDbContext> options) :
            base(options)
        {
            OnCreated();
        }
        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.ConfigureCmsKitManagement();

            CustomizeMapping(ref builder);

            base.OnModelCreating(builder);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        partial void OnCreated();
    }
}
