//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
using FS.CmsKitManagement.Attachments.EntityFrameworkCore;
using FS.CmsKit.ContentDefinitions.EntityFrameworkCore;
using FS.CmsKitManagement.ContentRecords.EntityFrameworkCore;
using FS.CmsKit.ContentEntities.EntityFrameworkCore;
using FS.CmsKit.ContentComposites.EntityFrameworkCore;
using FS.CmsKit.EntityMedias.EntityFrameworkCore;


namespace FS.CmsKitManagement.EntityFrameworkCore
{
    public static partial class CmsKitManagementDbContextModelCreatingExtensions
    {
        public static void ConfigureCmsKitManagement(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ConfigureAttachments();
            builder.ConfigureContentDefinitions();
            builder.ConfigureContentRecords();
            builder.ConfigureContentEntities();
            builder.ConfigureContentComposites();
            builder.ConfigureEntityMedias();

        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
