//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System.Reflection;
using System.Data.Common;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Volo.Abp.Data;
using Volo.Abp.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Volo.Abp.DependencyInjection;

namespace FS.CmsKitManagement.EntityFrameworkCore
{
    [ConnectionStringName(CmsKitManagementDbProperties.ConnectionStringName)]
    public partial interface ICmsKitManagementDbContext : IEfCoreDbContext,
        FS.CmsKitManagement.Attachments.EntityFrameworkCore.IAttachmentsDbContext,
        FS.CmsKit.ContentDefinitions.EntityFrameworkCore.IContentDefinitionsDbContext,
        FS.CmsKitManagement.ContentRecords.EntityFrameworkCore.IContentRecordsDbContext,
        FS.CmsKit.ContentEntities.EntityFrameworkCore.IContentEntitiesDbContext,
        FS.CmsKit.ContentComposites.EntityFrameworkCore.IContentCompositesDbContext,
        FS.CmsKit.EntityMedias.EntityFrameworkCore.IEntityMediasDbContext
    {
        //DbSet<FS.CmsKitManagement.Attachments.Attachment> Attachments { get; set; }
        //DbSet<FS.CmsKit.ContentDefinitions.ContentTypeDefinition> ContentTypeDefinitions { get; set; }
        //DbSet<FS.CmsKit.ContentDefinitions.ContentPartDefinition> ContentPartDefinitions { get; set; }
        //DbSet<FS.CmsKit.ContentDefinitions.ContentDefinition> ContentDefinitions { get; set; }
        //DbSet<FS.CmsKitManagement.ContentRecords.ContentTypeRecord> ContentTypeRecords { get; set; }
        //DbSet<FS.CmsKit.ContentEntities.ContentEntity> ContentEntities { get; set; }
        //DbSet<FS.CmsKit.ContentComposites.ContentItem> ContentItems { get; set; }
        //DbSet<FS.CmsKit.ContentComposites.ContentComposite> ContentComposites { get; set; }
        //DbSet<FS.CmsKit.ContentComposites.ImageComposite> ImageComposites { get; set; }
        //DbSet<FS.CmsKit.ContentComposites.AttachmentComposite> AttachmentComposites { get; set; }
        //DbSet<FS.CmsKit.ContentComposites.ContentComponent> ContentComponents { get; set; }
        //DbSet<FS.CmsKit.EntityMedias.EntityMedia> EntityMedia { get; set; }
        //DbSet<FS.CmsKit.EntityMedias.EntityMediaGroup> EntityMediaGroups { get; set; }
        //DbSet<FS.CmsKit.EntityMedias.EntityMediaItem> EntityMediaItems { get; set; }
    }
}
