//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKit.EntityMedias
{
    public partial class EntityMediaCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.CmsKit.EntityMedias.EntityMedia, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaWithDetailsDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaDto, 
            Guid, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGetListDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaCreateDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaUpdateDto>,
        IEntityMediaCrudAppService
    {
        private readonly IEntityMediaRepository _repository;

        public EntityMediaCrudAppService(IEntityMediaRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
