//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKit.EntityMedias
{
    public partial class EntityMediaGroupCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.CmsKit.EntityMedias.EntityMediaGroup, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGroupWithDetailsDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGroupDto, 
            Guid, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGroupGetListDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGroupCreateDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGroupUpdateDto>,
        IEntityMediaGroupCrudAppService
    {
        private readonly IEntityMediaGroupRepository _repository;

        public EntityMediaGroupCrudAppService(IEntityMediaGroupRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
