//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
using FS.Abp.Emailing.EntityFrameworkCore;


namespace FS.Abp.EmailingManagement.EntityFrameworkCore
{
    public static partial class EmailingManagementDbContextModelCreatingExtensions
    {
        public static void ConfigureEmailingManagement(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ConfigureEmailing();

        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
