//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FS.CmsKit.EntityMedias
{
    public partial interface IEntityMediaRepository : 
        Volo.Abp.Domain.Repositories.IRepository<FS.CmsKit.EntityMedias.EntityMedia,Guid>
    {

    }
}
