//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;

namespace FS.CmsKit.ContentDefinitions.EntityFrameworkCore
{
    public partial class ContentDefinitionConfiguration : IEntityTypeConfiguration<ContentDefinition> //auto-generated
    {
        private string tablePrefix;
        private string schema;
        public ContentDefinitionConfiguration(string tablePrefix, string schema)
        {
            this.tablePrefix = tablePrefix;
            this.schema = schema;
        }
        public void Configure(EntityTypeBuilder<ContentDefinition> builder)
        {
            builder.ToTable(tablePrefix + @"ContentDefinitions", schema);
            builder.Property<Guid>(@"Id").HasColumnName(@"Id").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();
            builder.Property(x => x.Version).HasColumnName(@"Version").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.IsPublish).HasColumnName(@"IsPublish").IsRequired().ValueGeneratedNever();
            builder.HasKey(@"Id");

            builder.ConfigureAuditedAggregateRoot();
            builder.HasIndex(x => x.CreationTime);

            CustomizeConfiguration(builder);
        }

        partial void CustomizeConfiguration(EntityTypeBuilder<ContentDefinition> builder);
    }
    public static partial class ContentDefinitionQueryableExtensions //auto-generated
    {
        public static IQueryable<ContentDefinition> IncludeDetails(this IQueryable<ContentDefinition> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }

            IQueryable<ContentDefinition> result = queryable
                .Include(x => x.ContentTypeDefinitions)
                .Include(x => x.ContentPartDefinitions);

            CustomizeIncludeDetails(ref result);

            return result;
        }

        static partial void CustomizeIncludeDetails(ref IQueryable<ContentDefinition> query);
    }
}
