//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;

namespace FS.CmsKit.ContentDefinitions.EntityFrameworkCore
{
    public partial class ContentPartDefinitionConfiguration : IEntityTypeConfiguration<ContentPartDefinition> //auto-generated
    {
        private string tablePrefix;
        private string schema;
        public ContentPartDefinitionConfiguration(string tablePrefix, string schema)
        {
            this.tablePrefix = tablePrefix;
            this.schema = schema;
        }
        public void Configure(EntityTypeBuilder<ContentPartDefinition> builder)
        {
            builder.ToTable(tablePrefix + @"ContentPartDefinitions", schema);
            builder.Property<Guid>(@"Id").HasColumnName(@"Id").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();
            builder.Property(x => x.ContentDefinitionId).HasColumnName(@"ContentDefinitionId").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Type).HasColumnName(@"Type").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.TemplateDefinitionName).HasColumnName(@"TemplateDefinitionName").IsRequired().ValueGeneratedNever();
            builder.HasKey(@"Id");

            builder.ConfigureAuditedAggregateRoot();
            builder.HasIndex(x => x.CreationTime);

            CustomizeConfiguration(builder);
        }

        partial void CustomizeConfiguration(EntityTypeBuilder<ContentPartDefinition> builder);
    }
    public static partial class ContentPartDefinitionQueryableExtensions //auto-generated
    {
        public static IQueryable<ContentPartDefinition> IncludeDetails(this IQueryable<ContentPartDefinition> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }

            IQueryable<ContentPartDefinition> result = queryable
                .Include(x => x.ContentPartFieldDefinitions);

            CustomizeIncludeDetails(ref result);

            return result;
        }

        static partial void CustomizeIncludeDetails(ref IQueryable<ContentPartDefinition> query);
    }
}
