//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.ComponentModel;
using System.Reflection;
using System.Data.Common;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Volo.Abp.Data;
using Volo.Abp.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Volo.Abp.DependencyInjection;

namespace FS.CmsKit.ContentDefinitions.EntityFrameworkCore
{
    public partial class ContentDefinitionsDbContext : AbpDbContext<ContentDefinitionsDbContext>, IContentDefinitionsDbContext
    {
        public DbSet<FS.CmsKit.ContentDefinitions.ContentTypeDefinition> ContentTypeDefinitions { get; set; }

        public DbSet<FS.CmsKit.ContentDefinitions.ContentTypePartDefinition> ContentTypePartDefinitions { get; set; }

        public DbSet<FS.CmsKit.ContentDefinitions.ContentPartDefinition> ContentPartDefinitions { get; set; }

        public DbSet<FS.CmsKit.ContentDefinitions.ContentPartFieldDefinition> ContentPartFieldDefinitions { get; set; }

        public DbSet<FS.CmsKit.ContentDefinitions.ContentDefinition> ContentDefinitions { get; set; }

        public ContentDefinitionsDbContext(DbContextOptions<ContentDefinitionsDbContext> options)
            : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            builder.ConfigureContentDefinitions();

            CustomizeMapping(ref builder);

            base.OnModelCreating(builder);
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        partial void OnCreated();
    }
}
