//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;

namespace FS.CmsKit.ContentDefinitions.EntityFrameworkCore
{
    public static partial class ContentDefinitionsDbContextModelCreatingExtensions
    {
        public static void ConfigureContentDefinitions(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.CmsKit.ContentDefinitions.ContentTypeDefinition>(new FS.CmsKit.ContentDefinitions.EntityFrameworkCore.ContentTypeDefinitionConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKit.ContentDefinitions.ContentTypePartDefinition>(new FS.CmsKit.ContentDefinitions.EntityFrameworkCore.ContentTypePartDefinitionConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKit.ContentDefinitions.ContentPartDefinition>(new FS.CmsKit.ContentDefinitions.EntityFrameworkCore.ContentPartDefinitionConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKit.ContentDefinitions.ContentPartFieldDefinition>(new FS.CmsKit.ContentDefinitions.EntityFrameworkCore.ContentPartFieldDefinitionConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKit.ContentDefinitions.ContentDefinition>(new FS.CmsKit.ContentDefinitions.EntityFrameworkCore.ContentDefinitionConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
