//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Threading.Tasks;
using FS.CmsKit.ContentDefinitions.EntityFrameworkCore;

namespace FS.CmsKit.ContentDefinitions.EntityFrameworkCore
{
    public partial class EfCoreContentPartDefinitionRepository : 
        EfCoreRepository<IContentDefinitionsDbContext,FS.CmsKit.ContentDefinitions.ContentPartDefinition,Guid>,
        IContentPartDefinitionRepository
    {
        public EfCoreContentPartDefinitionRepository(IDbContextProvider<IContentDefinitionsDbContext> dbContextProvider)
            : base(dbContextProvider) { }
        public override async Task<IQueryable<FS.CmsKit.ContentDefinitions.ContentPartDefinition>> WithDetailsAsync()
        {
            return (await GetQueryableAsync()).IncludeDetails();
        }
    }
}
