//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Services;

namespace FS.CmsKit.ContentDefinitions
{
    public partial class ContentDefinitionsStore : DomainService, IContentDefinitionsStore //auto-generated
    {
        public IContentTypeDefinitionRepository ContentTypeDefinition => this.LazyServiceProvider.LazyGetRequiredService<IContentTypeDefinitionRepository>();
        public IContentTypePartDefinitionRepository ContentTypePartDefinition => this.LazyServiceProvider.LazyGetRequiredService<IContentTypePartDefinitionRepository>();
        public IContentPartDefinitionRepository ContentPartDefinition => this.LazyServiceProvider.LazyGetRequiredService<IContentPartDefinitionRepository>();
        public IContentPartFieldDefinitionRepository ContentPartFieldDefinition => this.LazyServiceProvider.LazyGetRequiredService<IContentPartFieldDefinitionRepository>();
        public IContentDefinitionRepository ContentDefinition => this.LazyServiceProvider.LazyGetRequiredService<IContentDefinitionRepository>();
    }
}
