//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Volo.Abp.Data;

namespace FS.CmsKitManagement.ContentRecords
{
    public partial class ContentPartRecord : 
        Volo.Abp.Domain.Entities.Auditing.AuditedEntity<Guid>
    {

        public ContentPartRecord()
        {
            this.ContentPartFieldRecords = new List<ContentPartFieldRecord>();
            OnCreated();
        }

        public ContentPartRecord(System.Guid id) : this()
        {
            this.Id = id;
        }

        public virtual System.Guid ContentPartDefinitionId
        {
            get;
            set;
        }

        public virtual System.Guid? TenantId
        {
            get;
            set;
        }

        public virtual System.Guid ContentTypeRecordId
        {
            get;
            set;
        }

        public virtual IList<ContentPartFieldRecord> ContentPartFieldRecords
        {
            get;
            set;
        }


        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
