//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Services;

namespace FS.CmsKitManagement.ContentRecords
{
    public partial interface IContentRecordsStore : IDomainService //auto-generated
    {
        IContentTypeRecordRepository ContentTypeRecord { get; }
        IContentPartFieldRecordRepository ContentPartFieldRecord { get; }
        IContentPartRecordRepository ContentPartRecord { get; }
    }
}
