//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.CmsKit.EntityMedias.Dtos
{
    public partial class EntityMediaItemCreateDtoValidator : AbstractValidator<EntityMediaItemCreateDto>
    {
        public EntityMediaItemCreateDtoValidator()
        {
            RuleFor(p => p.Name)
                .NotNull()
                ;
            RuleFor(p => p.EntityId)
                .Length(0, 64)
                .NotNull()
                ;
            RuleFor(p => p.EntityType)
                .Length(0, 64)
                .NotNull()
                ;
            RuleFor(p => p.MediaDescriptorId)
                .NotNull()
                ;
            RuleFor(p => p.EntityMediaGroupName)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class EntityMediaItemUpdateDtoValidator : AbstractValidator<EntityMediaItemUpdateDto>
    {
        public EntityMediaItemUpdateDtoValidator()
        {
            RuleFor(p => p.Name)
                .NotNull()
                ;
            RuleFor(p => p.EntityId)
                .Length(0, 64)
                .NotNull()
                ;
            RuleFor(p => p.EntityType)
                .Length(0, 64)
                .NotNull()
                ;
            RuleFor(p => p.MediaDescriptorId)
                .NotNull()
                ;
            RuleFor(p => p.EntityMediaGroupName)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
