//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.EntityMedias.Dtos
{

    public partial class EntityMediaDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string EntityType { get; set; }

    }

    public partial class EntityMediaCreateDto
    {
        public virtual string EntityType { get; set; }

    }

    public partial class EntityMediaUpdateDto
    {
        public virtual string EntityType { get; set; }

    }

    public partial class EntityMediaGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class EntityMediaWithDetailsDto : EntityMediaDto
    {
        public List<EntityMediaGroupDto> EntityMediaGroups { get; set; }

    }
}
