//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.CmsKit.EntityMedias.Dtos
{
    public partial class EntityMediaGroupCreateDtoValidator : AbstractValidator<EntityMediaGroupCreateDto>
    {
        public EntityMediaGroupCreateDtoValidator()
        {
            RuleFor(p => p.Name)
                .NotNull()
                ;
            RuleFor(p => p.MediaType)
                .NotNull()
                ;
            RuleFor(p => p.EntityMediaId)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class EntityMediaGroupUpdateDtoValidator : AbstractValidator<EntityMediaGroupUpdateDto>
    {
        public EntityMediaGroupUpdateDtoValidator()
        {
            RuleFor(p => p.Name)
                .NotNull()
                ;
            RuleFor(p => p.MediaType)
                .NotNull()
                ;
            RuleFor(p => p.EntityMediaId)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
