//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.EntityMedias.Dtos
{

    public partial class EntityMediaGroupDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string Name { get; set; }

        public virtual FS.CmsKit.EntityMedias.MediaType MediaType { get; set; }

        public virtual System.Guid EntityMediaId { get; set; }

    }

    public partial class EntityMediaGroupCreateDto
    {
        public virtual string Name { get; set; }

        public virtual FS.CmsKit.EntityMedias.MediaType MediaType { get; set; }

        public virtual System.Guid EntityMediaId { get; set; }

    }

    public partial class EntityMediaGroupUpdateDto
    {
        public virtual string Name { get; set; }

        public virtual FS.CmsKit.EntityMedias.MediaType MediaType { get; set; }

        public virtual System.Guid EntityMediaId { get; set; }

    }

    public partial class EntityMediaGroupGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class EntityMediaGroupWithDetailsDto : EntityMediaGroupDto
    {
        public EntityMediaDto EntityMedia { get; set; }

    }
}
