//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKit.ContentEntities
{
    public partial interface IContentEntityCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.CmsKit.ContentEntities.Dtos.ContentEntityWithDetailsDto, 
            FS.CmsKit.ContentEntities.Dtos.ContentEntityDto, 
            Guid, 
            FS.CmsKit.ContentEntities.Dtos.ContentEntityGetListDto, 
            FS.CmsKit.ContentEntities.Dtos.ContentEntityCreateDto, 
            FS.CmsKit.ContentEntities.Dtos.ContentEntityUpdateDto>
    {

    }
}
