//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;

namespace FS.CmsKit.ContentComposites.EntityFrameworkCore
{
    public partial class ContentComponentConfiguration : IEntityTypeConfiguration<ContentComponent> //auto-generated
    {
        private string tablePrefix;
        private string schema;
        public ContentComponentConfiguration(string tablePrefix, string schema)
        {
            this.tablePrefix = tablePrefix;
            this.schema = schema;
        }
        public void Configure(EntityTypeBuilder<ContentComponent> builder)
        {
            builder.ToTable(tablePrefix + @"ContentComponents", schema);
            builder.HasDiscriminator<string>(@"Discriminator");
            builder.Property<Guid>(@"Id").HasColumnName(@"Id").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();
            builder.Property(x => x.ContentEntityId).HasColumnName(@"ContentEntityId").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.Property(x => x.Code).HasColumnName(@"Code").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ParentId).HasColumnName(@"ParentId").ValueGeneratedNever();
            builder.Property(x => x.Level).HasColumnName(@"Level").ValueGeneratedNever();
            builder.Property(x => x.DisplayName).HasColumnName(@"DisplayName").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ContentComponentDiscriminator).HasColumnName(@"ContentComponentDiscriminator").IsRequired().ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasOne(x => x.Parent).WithMany(op => op.Children).IsRequired(false).HasForeignKey(@"ParentId");

            builder.ConfigureAuditedAggregateRoot();
            builder.HasIndex(x => x.CreationTime);

            CustomizeConfiguration(builder);
        }

        partial void CustomizeConfiguration(EntityTypeBuilder<ContentComponent> builder);
    }
    public static partial class ContentComponentQueryableExtensions //auto-generated
    {
        public static IQueryable<ContentComponent> IncludeDetails(this IQueryable<ContentComponent> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }

            IQueryable<ContentComponent> result = queryable
                .Include(x => x.Children)
                .Include(x => x.Parent);

            CustomizeIncludeDetails(ref result);

            return result;
        }

        static partial void CustomizeIncludeDetails(ref IQueryable<ContentComponent> query);
    }
}
