//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;

namespace FS.CmsKit.ContentComposites.EntityFrameworkCore
{
    public static partial class ContentCompositesDbContextModelCreatingExtensions
    {
        public static void ConfigureContentComposites(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.CmsKit.ContentComposites.ContentItem>(new FS.CmsKit.ContentComposites.EntityFrameworkCore.ContentItemConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKit.ContentComposites.ContentComposite>(new FS.CmsKit.ContentComposites.EntityFrameworkCore.ContentCompositeConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKit.ContentComposites.ImageComposite>(new FS.CmsKit.ContentComposites.EntityFrameworkCore.ImageCompositeConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKit.ContentComposites.AttachmentComposite>(new FS.CmsKit.ContentComposites.EntityFrameworkCore.AttachmentCompositeConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKit.ContentComposites.ContentComponent>(new FS.CmsKit.ContentComposites.EntityFrameworkCore.ContentComponentConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
