//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.CmsKit.EntityMedias.Dtos
{
    public partial class EntityMediaGroupAutoMapperProfile : Profile
    {
        public EntityMediaGroupAutoMapperProfile()
        {
            CreateMap<FS.CmsKit.EntityMedias.EntityMediaGroup, EntityMediaGroupDto>()
            .ReverseMap();
        
            CreateMap<EntityMediaGroupCreateDto, FS.CmsKit.EntityMedias.EntityMediaGroup>();
        
            CreateMap<EntityMediaGroupUpdateDto, FS.CmsKit.EntityMedias.EntityMediaGroup>();
        
            CreateMap<FS.CmsKit.EntityMedias.EntityMediaGroup, EntityMediaGroupWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
