//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Abp.Emailing.Dtos
{
    public partial class MailMessageTemplateAutoMapperProfile : Profile
    {
        public MailMessageTemplateAutoMapperProfile()
        {
            CreateMap<FS.Abp.Emailing.MailMessageTemplate, MailMessageTemplateDto>()
            .ReverseMap();
        
            CreateMap<MailMessageTemplateCreateDto, FS.Abp.Emailing.MailMessageTemplate>();
        
            CreateMap<MailMessageTemplateUpdateDto, FS.Abp.Emailing.MailMessageTemplate>();
        
            CreateMap<FS.Abp.Emailing.MailMessageTemplate, MailMessageTemplateWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
