//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.CmsKit.ContentComposites.Dtos
{
    namespace V1
    {
        public partial class ContentComponentAutoMapperProfile : Profile
        {
            public ContentComponentAutoMapperProfile()
            {

                CreateMap<V1.ContentComponentPatchDto, FS.CmsKit.ContentComposites.ContentComponent>()
                .Include<FS.CmsKit.ContentComposites.Dtos.V1.ContentItemPatchDto, FS.CmsKit.ContentComposites.ContentItem>()
                .Include<FS.CmsKit.ContentComposites.Dtos.V1.ContentCompositePatchDto, FS.CmsKit.ContentComposites.ContentComposite>();

                CustomizeConfiguration();
            }
            partial void CustomizeConfiguration();
        }
    }


}
