//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Threading.Tasks;
using FS.CmsKit.EntityMedias.EntityFrameworkCore;

namespace FS.CmsKit.EntityMedias.EntityFrameworkCore
{
    public partial class EfCoreEntityMediaRepository : 
        EfCoreRepository<IEntityMediasDbContext,FS.CmsKit.EntityMedias.EntityMedia,Guid>,
        IEntityMediaRepository
    {
        public EfCoreEntityMediaRepository(IDbContextProvider<IEntityMediasDbContext> dbContextProvider)
            : base(dbContextProvider) { }
        public override async Task<IQueryable<FS.CmsKit.EntityMedias.EntityMedia>> WithDetailsAsync()
        {
            return (await GetQueryableAsync()).IncludeDetails();
        }
    }
}
