//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;

namespace FS.CmsKit.EntityMedias.EntityFrameworkCore
{
    public partial class EntityMediaGroupConfiguration : IEntityTypeConfiguration<EntityMediaGroup> //auto-generated
    {
        private string tablePrefix;
        private string schema;
        public EntityMediaGroupConfiguration(string tablePrefix, string schema)
        {
            this.tablePrefix = tablePrefix;
            this.schema = schema;
        }
        public void Configure(EntityTypeBuilder<EntityMediaGroup> builder)
        {
            builder.ToTable(tablePrefix + @"EntityMediaGroups", schema);
            builder.Property<Guid>(@"Id").HasColumnName(@"Id").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();
            builder.Property(x => x.MediaType).HasColumnName(@"MediaType").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.EntityMediaId).HasColumnName(@"EntityMediaId").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.HasKey(@"Id");
            builder.HasOne(x => x.EntityMedia).WithMany(op => op.EntityMediaGroups).IsRequired(true).HasForeignKey(@"EntityMediaId");

            builder.ConfigureAuditedAggregateRoot();
            builder.HasIndex(x => x.CreationTime);

            CustomizeConfiguration(builder);
        }

        partial void CustomizeConfiguration(EntityTypeBuilder<EntityMediaGroup> builder);
    }
    public static partial class EntityMediaGroupQueryableExtensions //auto-generated
    {
        public static IQueryable<EntityMediaGroup> IncludeDetails(this IQueryable<EntityMediaGroup> queryable, bool include = true)
        {
            if (!include)
            {
                return queryable;
            }

            IQueryable<EntityMediaGroup> result = queryable
                .Include(x => x.EntityMedia);

            CustomizeIncludeDetails(ref result);

            return result;
        }

        static partial void CustomizeIncludeDetails(ref IQueryable<EntityMediaGroup> query);
    }
}
