//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;

namespace FS.CmsKit.EntityMedias.EntityFrameworkCore
{
    public static partial class EntityMediasDbContextModelCreatingExtensions
    {
        public static void ConfigureEntityMedias(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.CmsKit.EntityMedias.EntityMedia>(new FS.CmsKit.EntityMedias.EntityFrameworkCore.EntityMediaConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKit.EntityMedias.EntityMediaGroup>(new FS.CmsKit.EntityMedias.EntityFrameworkCore.EntityMediaGroupConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKit.EntityMedias.EntityMediaItem>(new FS.CmsKit.EntityMedias.EntityFrameworkCore.EntityMediaItemConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
