//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.ContentDefinitions.Dtos
{

    public partial class ContentPartDefinitionDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual System.Guid? ContentDefinitionId { get; set; }

        public virtual string Name { get; set; }

        public virtual string Type { get; set; }

        public virtual string TemplateDefinitionName { get; set; }

    }

    public partial class ContentPartDefinitionCreateDto
    {
        public virtual System.Guid? ContentDefinitionId { get; set; }

        public virtual string Name { get; set; }

        public virtual string Type { get; set; }

        public virtual string TemplateDefinitionName { get; set; }

    }

    public partial class ContentPartDefinitionUpdateDto
    {
        public virtual System.Guid? ContentDefinitionId { get; set; }

        public virtual string Name { get; set; }

        public virtual string Type { get; set; }

        public virtual string TemplateDefinitionName { get; set; }

    }

    public partial class ContentPartDefinitionGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class ContentPartDefinitionWithDetailsDto : ContentPartDefinitionDto
    {
        public List<ContentPartFieldDefinitionDto> ContentPartFieldDefinitions { get; set; }

    }
}
