//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.CmsKit.ContentDefinitions.Dtos
{
    public partial class ContentTypeDefinitionCreateDtoValidator : AbstractValidator<ContentTypeDefinitionCreateDto>
    {
        public ContentTypeDefinitionCreateDtoValidator()
        {
            RuleFor(p => p.ContentDefinitionId)
                ;
            RuleFor(p => p.EntityType)
                .Length(0, 64)
                .NotNull()
                ;
            RuleFor(p => p.EntityId)
                .Length(0, 64)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class ContentTypeDefinitionUpdateDtoValidator : AbstractValidator<ContentTypeDefinitionUpdateDto>
    {
        public ContentTypeDefinitionUpdateDtoValidator()
        {
            RuleFor(p => p.ContentDefinitionId)
                ;
            RuleFor(p => p.EntityType)
                .Length(0, 64)
                .NotNull()
                ;
            RuleFor(p => p.EntityId)
                .Length(0, 64)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
