//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.ContentDefinitions.Dtos
{

    public partial class ContentDefinitionDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string Version { get; set; }

        public virtual bool IsPublish { get; set; }

    }

    public partial class ContentDefinitionCreateDto
    {
        public virtual string Version { get; set; }

        public virtual bool IsPublish { get; set; }

    }

    public partial class ContentDefinitionUpdateDto
    {
        public virtual string Version { get; set; }

        public virtual bool IsPublish { get; set; }

    }

    public partial class ContentDefinitionGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class ContentDefinitionWithDetailsDto : ContentDefinitionDto
    {
        public List<ContentTypeDefinitionDto> ContentTypeDefinitions { get; set; }

        public List<ContentPartDefinitionDto> ContentPartDefinitions { get; set; }

    }
}
