//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.CmsKit.ContentDefinitions.Dtos
{
    public partial class ContentDefinitionCreateDtoValidator : AbstractValidator<ContentDefinitionCreateDto>
    {
        public ContentDefinitionCreateDtoValidator()
        {
            RuleFor(p => p.Version)
                .NotNull()
                ;
            RuleFor(p => p.IsPublish)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class ContentDefinitionUpdateDtoValidator : AbstractValidator<ContentDefinitionUpdateDto>
    {
        public ContentDefinitionUpdateDtoValidator()
        {
            RuleFor(p => p.Version)
                .NotNull()
                ;
            RuleFor(p => p.IsPublish)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
