//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.ContentDefinitions.Dtos
{

    public partial class ContentPartFieldDefinitionDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string Name { get; set; }

        public virtual string Type { get; set; }

        public virtual System.Guid ContentPartDefinitionId { get; set; }

    }

    public partial class ContentPartFieldDefinitionCreateDto
    {
        public virtual string Name { get; set; }

        public virtual string Type { get; set; }

        public virtual System.Guid ContentPartDefinitionId { get; set; }

    }

    public partial class ContentPartFieldDefinitionUpdateDto
    {
        public virtual string Name { get; set; }

        public virtual string Type { get; set; }

        public virtual System.Guid ContentPartDefinitionId { get; set; }

    }

    public partial class ContentPartFieldDefinitionGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class ContentPartFieldDefinitionWithDetailsDto : ContentPartFieldDefinitionDto
    {
    }
}
