//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.ContentDefinitions.Dtos
{

    public partial class ContentTypePartDefinitionDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual System.Guid ContentTypeDefinitionId { get; set; }

        public virtual System.Guid ContentPartDefinitionId { get; set; }

    }

    public partial class ContentTypePartDefinitionCreateDto
    {
        public virtual System.Guid ContentTypeDefinitionId { get; set; }

        public virtual System.Guid ContentPartDefinitionId { get; set; }

    }

    public partial class ContentTypePartDefinitionUpdateDto
    {
        public virtual System.Guid ContentTypeDefinitionId { get; set; }

        public virtual System.Guid ContentPartDefinitionId { get; set; }

    }

    public partial class ContentTypePartDefinitionGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class ContentTypePartDefinitionWithDetailsDto : ContentTypePartDefinitionDto
    {
    }
}
