//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.CmsKit.ContentDefinitions.Dtos
{
    public partial class ContentTypePartDefinitionCreateDtoValidator : AbstractValidator<ContentTypePartDefinitionCreateDto>
    {
        public ContentTypePartDefinitionCreateDtoValidator()
        {
            RuleFor(p => p.ContentTypeDefinitionId)
                .NotNull()
                ;
            RuleFor(p => p.ContentPartDefinitionId)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class ContentTypePartDefinitionUpdateDtoValidator : AbstractValidator<ContentTypePartDefinitionUpdateDto>
    {
        public ContentTypePartDefinitionUpdateDtoValidator()
        {
            RuleFor(p => p.ContentTypeDefinitionId)
                .NotNull()
                ;
            RuleFor(p => p.ContentPartDefinitionId)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
