//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.Social.Codes.Dtos
{
    public partial class CodeAutoMapperProfile : Profile
    {
        public CodeAutoMapperProfile()
        {
            CreateMap<FS.Social.Codes.Code, CodeDto>()
            .ReverseMap();
        
            CreateMap<CodeCreateDto, FS.Social.Codes.Code>();
        
            CreateMap<CodeUpdateDto, FS.Social.Codes.Code>();
        
            CreateMap<FS.Social.Codes.Code, CodeWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
