//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.Social.Codes.Dtos
{
    public partial class CodeCreateDtoValidator : AbstractValidator<CodeCreateDto>
    {
        public CodeCreateDtoValidator()
        {
            RuleFor(p => p.Name)
                .NotNull()
                ;
            RuleFor(p => p.Value)
                .NotNull()
                ;
            RuleFor(p => p.ProviderName)
                ;
            RuleFor(p => p.ProviderKey)
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class CodeUpdateDtoValidator : AbstractValidator<CodeUpdateDto>
    {
        public CodeUpdateDtoValidator()
        {
            RuleFor(p => p.Name)
                .NotNull()
                ;
            RuleFor(p => p.Value)
                .NotNull()
                ;
            RuleFor(p => p.ProviderName)
                ;
            RuleFor(p => p.ProviderKey)
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
