//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.Social.Codes.Dtos
{

    public partial class CodeDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string Name { get; set; }

        public virtual string Value { get; set; }

        public virtual string ProviderName { get; set; }

        public virtual string ProviderKey { get; set; }

    }

    public partial class CodeCreateDto
    {
        public virtual string Name { get; set; }

        public virtual string Value { get; set; }

        public virtual string ProviderName { get; set; }

        public virtual string ProviderKey { get; set; }

    }

    public partial class CodeUpdateDto
    {
        public virtual string Name { get; set; }

        public virtual string Value { get; set; }

        public virtual string ProviderName { get; set; }

        public virtual string ProviderKey { get; set; }

    }

    public partial class CodeGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class CodeWithDetailsDto : CodeDto
    {
    }
}
