//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;

namespace FS.CmsKitManagement.ContentRecords.EntityFrameworkCore
{
    public static partial class ContentRecordsDbContextModelCreatingExtensions
    {
        public static void ConfigureContentRecords(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.CmsKitManagement.ContentRecords.ContentTypeRecord>(new FS.CmsKitManagement.ContentRecords.EntityFrameworkCore.ContentTypeRecordConfiguration(CmsKitManagementDbProperties.DbTablePrefix,CmsKitManagementDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKitManagement.ContentRecords.ContentPartFieldRecord>(new FS.CmsKitManagement.ContentRecords.EntityFrameworkCore.ContentPartFieldRecordConfiguration(CmsKitManagementDbProperties.DbTablePrefix,CmsKitManagementDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.CmsKitManagement.ContentRecords.ContentPartRecord>(new FS.CmsKitManagement.ContentRecords.EntityFrameworkCore.ContentPartRecordConfiguration(CmsKitManagementDbProperties.DbTablePrefix,CmsKitManagementDbProperties.DbSchema));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
