//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;

namespace FS.CmsKitManagement.ContentRecords.EntityFrameworkCore
{
    public partial class ContentPartFieldRecordConfiguration : IEntityTypeConfiguration<ContentPartFieldRecord> //auto-generated
    {
        private string tablePrefix;
        private string schema;
        public ContentPartFieldRecordConfiguration(string tablePrefix, string schema)
        {
            this.tablePrefix = tablePrefix;
            this.schema = schema;
        }
        public void Configure(EntityTypeBuilder<ContentPartFieldRecord> builder)
        {
            builder.ToTable(tablePrefix + @"ContentPartFieldRecords", schema);
            builder.Property<Guid>(@"Id").HasColumnName(@"Id").HasColumnType(@"uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.TenantId).HasColumnName(@"TenantId").ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Value).HasColumnName(@"Value").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ContentPartRecordId).HasColumnName(@"ContentPartRecordId").HasColumnType(@"uniqueidentifier").ValueGeneratedNever();
            builder.HasKey(@"Id");

            builder.ConfigureAudited();

            CustomizeConfiguration(builder);
        }

        partial void CustomizeConfiguration(EntityTypeBuilder<ContentPartFieldRecord> builder);
    }
    public static partial class ContentPartFieldRecordQueryableExtensions //auto-generated
    {
    }
}
