//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.Attachments
{
    public partial class AttachmentCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.CmsKitManagement.Attachments.Attachment, 
            FS.CmsKitManagement.Attachments.Dtos.AttachmentWithDetailsDto, 
            FS.CmsKitManagement.Attachments.Dtos.AttachmentDto, 
            Guid, 
            FS.CmsKitManagement.Attachments.Dtos.AttachmentGetListDto, 
            FS.CmsKitManagement.Attachments.Dtos.AttachmentCreateDto, 
            FS.CmsKitManagement.Attachments.Dtos.AttachmentUpdateDto>,
        IAttachmentCrudAppService
    {
        private readonly IAttachmentRepository _repository;

        public AttachmentCrudAppService(IAttachmentRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
