//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKit.ContentComposites.Dtos
{
    namespace V1 
    {
        public partial class ContentCompositePatchDto : FS.CmsKit.ContentComposites.Dtos.V1.ContentComponentPatchDto
        {
        }
    }

}
