//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.Entity.Localization;
using FS.Entity.Permissions;

namespace FS.Entity.MultiLinguals.Permissions
{
    public partial class MultiLingualsPermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var group = context.GetGroup(EntityPermissions.GroupName);

            var MultiLingualTranslation = group.AddPermission(MultiLingualsPermissionNames.MultiLingualTranslation.Default,L(MultiLingualsPermissionNames.MultiLingualTranslation.Default));
            MultiLingualTranslation.AddChild(MultiLingualsPermissionNames.MultiLingualTranslation.Create , L("DisplayName:MultiLingualTranslation.Create"));
            MultiLingualTranslation.AddChild(MultiLingualsPermissionNames.MultiLingualTranslation.Update , L("DisplayName:MultiLingualTranslation.Update"));
            MultiLingualTranslation.AddChild(MultiLingualsPermissionNames.MultiLingualTranslation.Delete , L("DisplayName:MultiLingualTranslation.Delete"));

            var MultiLingual = group.AddPermission(MultiLingualsPermissionNames.MultiLingual.Default,L(MultiLingualsPermissionNames.MultiLingual.Default));
            MultiLingual.AddChild(MultiLingualsPermissionNames.MultiLingual.Create , L("DisplayName:MultiLingual.Create"));
            MultiLingual.AddChild(MultiLingualsPermissionNames.MultiLingual.Update , L("DisplayName:MultiLingual.Update"));
            MultiLingual.AddChild(MultiLingualsPermissionNames.MultiLingual.Delete , L("DisplayName:MultiLingual.Delete"));

            CustomizeDefine(context);
        }

        partial void CustomizeDefine(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context);

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<EntityResource>(name);
        }
    }
}
