//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;

namespace FS.CmsKit.ContentEntities.EntityFrameworkCore
{
    public static partial class ContentEntitiesDbContextModelCreatingExtensions
    {
        public static void ConfigureContentEntities(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.CmsKit.ContentEntities.ContentEntity>(new FS.CmsKit.ContentEntities.EntityFrameworkCore.ContentEntityConfiguration(CmsKitDbProperties.DbTablePrefix,CmsKitDbProperties.DbSchema));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
