//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Volo.Abp.EntityFrameworkCore;
using Volo.Abp.Domain.Repositories.EntityFrameworkCore;
using System.Threading.Tasks;
using FS.CmsKit.ContentEntities.EntityFrameworkCore;

namespace FS.CmsKit.ContentEntities.EntityFrameworkCore
{
    public partial class EfCoreContentEntityRepository : 
        EfCoreRepository<IContentEntitiesDbContext,FS.CmsKit.ContentEntities.ContentEntity,Guid>,
        IContentEntityRepository
    {
        public EfCoreContentEntityRepository(IDbContextProvider<IContentEntitiesDbContext> dbContextProvider)
            : base(dbContextProvider) { }
    }
}
