//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.FormManagement.EntityForms
{
    public partial class EntityFormCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<FS.FormManagement.EntityForms.EntityForm, FS.FormManagement.EntityForms.Dtos.EntityFormWithDetailsDto, Guid, FS.FormManagement.EntityForms.Dtos.EntityFormGetListDto, FS.FormManagement.EntityForms.Dtos.EntityFormCreateDto, FS.FormManagement.EntityForms.Dtos.EntityFormUpdateDto>,
        IEntityFormCrudAppService
    {
        private readonly IEntityFormRepository _repository;

        public EntityFormCrudAppService(IEntityFormRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
