//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;

namespace FS.CmsKitManagement.Attachments.EntityFrameworkCore
{
    public static partial class AttachmentsDbContextModelCreatingExtensions
    {
        public static void ConfigureAttachments(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.CmsKitManagement.Attachments.Attachment>(new FS.CmsKitManagement.Attachments.EntityFrameworkCore.AttachmentConfiguration(CmsKitManagementDbProperties.DbTablePrefix,CmsKitManagementDbProperties.DbSchema));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
