//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.CmsKitManagement.Attachments.Permissions
{
    public class AttachmentsPermissionNames
    {
        public const string ModuleName = "FS.CmsKitManagement.Attachments";
        public static class Attachment
        {
            public const string Default = ModuleName + ".Attachment";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(AttachmentsPermissionNames));
        }
    }
}
