//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.CmsKitManagement.Localization;
using FS.CmsKitManagement.Permissions;

namespace FS.CmsKitManagement.Attachments.Permissions
{
    public partial class AttachmentsPermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var group = context.GetGroup(CmsKitManagementPermissions.GroupName);

            var Attachment = group.AddPermission(AttachmentsPermissionNames.Attachment.Default,L(AttachmentsPermissionNames.Attachment.Default));
            Attachment.AddChild(AttachmentsPermissionNames.Attachment.Create , L("DisplayName:Attachment.Create"));
            Attachment.AddChild(AttachmentsPermissionNames.Attachment.Update , L("DisplayName:Attachment.Update"));
            Attachment.AddChild(AttachmentsPermissionNames.Attachment.Delete , L("DisplayName:Attachment.Delete"));

            CustomizeDefine(context);
        }

        partial void CustomizeDefine(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context);

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<CmsKitManagementResource>(name);
        }
    }
}
