//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKit.ContentDefinitions
{
    public partial interface IContentDefinitionCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.CmsKit.ContentDefinitions.Dtos.ContentDefinitionWithDetailsDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentDefinitionDto, 
            Guid, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentDefinitionGetListDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentDefinitionCreateDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentDefinitionUpdateDto>
    {

    }
}
