//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.CmsKitManagement.ContentRecords.Dtos
{
    public partial class ContentPartFieldRecordAutoMapperProfile : Profile
    {
        public ContentPartFieldRecordAutoMapperProfile()
        {
            CreateMap<FS.CmsKitManagement.ContentRecords.ContentPartFieldRecord, ContentPartFieldRecordDto>()
            .ReverseMap();
        
            CreateMap<ContentPartFieldRecordCreateDto, FS.CmsKitManagement.ContentRecords.ContentPartFieldRecord>();
        
            CreateMap<ContentPartFieldRecordUpdateDto, FS.CmsKitManagement.ContentRecords.ContentPartFieldRecord>();
        
            CreateMap<FS.CmsKitManagement.ContentRecords.ContentPartFieldRecord, ContentPartFieldRecordWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
