//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.CmsKitManagement.ContentRecords.Dtos
{
    public partial class ContentTypeRecordAutoMapperProfile : Profile
    {
        public ContentTypeRecordAutoMapperProfile()
        {
            CreateMap<FS.CmsKitManagement.ContentRecords.ContentTypeRecord, ContentTypeRecordDto>()
            .ReverseMap();
        
            CreateMap<ContentTypeRecordCreateDto, FS.CmsKitManagement.ContentRecords.ContentTypeRecord>();
        
            CreateMap<ContentTypeRecordUpdateDto, FS.CmsKitManagement.ContentRecords.ContentTypeRecord>();
        
            CreateMap<FS.CmsKitManagement.ContentRecords.ContentTypeRecord, ContentTypeRecordWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
