//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Entity.EntityDefaults
{
    public partial interface IEntityDefaultCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.Entity.EntityDefaults.Dtos.EntityDefaultWithDetailsDto, 
            FS.Entity.EntityDefaults.Dtos.EntityDefaultDto, 
            Guid, 
            FS.Entity.EntityDefaults.Dtos.EntityDefaultGetListDto, 
            FS.Entity.EntityDefaults.Dtos.EntityDefaultCreateDto, 
            FS.Entity.EntityDefaults.Dtos.EntityDefaultUpdateDto>
    {

    }
}
