//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.Attachments
{
    public partial interface IAttachmentCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.CmsKitManagement.Attachments.Dtos.AttachmentWithDetailsDto, 
            FS.CmsKitManagement.Attachments.Dtos.AttachmentDto, 
            Guid, 
            FS.CmsKitManagement.Attachments.Dtos.AttachmentGetListDto, 
            FS.CmsKitManagement.Attachments.Dtos.AttachmentCreateDto, 
            FS.CmsKitManagement.Attachments.Dtos.AttachmentUpdateDto>
    {

    }
}
