//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.ContentRecords
{
    public partial interface IContentTypeRecordCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.CmsKitManagement.ContentRecords.Dtos.ContentTypeRecordWithDetailsDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentTypeRecordDto, 
            Guid, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentTypeRecordGetListDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentTypeRecordCreateDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentTypeRecordUpdateDto>
    {

    }
}
