//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.ContentRecords
{
    public partial interface IContentPartRecordCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartRecordWithDetailsDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartRecordDto, 
            Guid, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartRecordGetListDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartRecordCreateDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartRecordUpdateDto>
    {

    }
}
