//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.ContentRecords
{
    public partial interface IContentPartFieldRecordCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartFieldRecordWithDetailsDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartFieldRecordDto, 
            Guid, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartFieldRecordGetListDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartFieldRecordCreateDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartFieldRecordUpdateDto>
    {

    }
}
