//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.CmsKitManagement.ContentRecords.Dtos
{
    public partial class ContentPartFieldRecordCreateDtoValidator : AbstractValidator<ContentPartFieldRecordCreateDto>
    {
        public ContentPartFieldRecordCreateDtoValidator()
        {
            RuleFor(p => p.TenantId)
                ;
            RuleFor(p => p.Name)
                .NotNull()
                ;
            RuleFor(p => p.Value)
                .NotNull()
                ;
            RuleFor(p => p.ContentPartRecordId)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class ContentPartFieldRecordUpdateDtoValidator : AbstractValidator<ContentPartFieldRecordUpdateDto>
    {
        public ContentPartFieldRecordUpdateDtoValidator()
        {
            RuleFor(p => p.TenantId)
                ;
            RuleFor(p => p.Name)
                .NotNull()
                ;
            RuleFor(p => p.Value)
                .NotNull()
                ;
            RuleFor(p => p.ContentPartRecordId)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
