//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKitManagement.ContentRecords.Dtos
{

    public partial class ContentTypeRecordDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual System.Guid ContentTypeDefinitionId { get; set; }

    }

    public partial class ContentTypeRecordCreateDto
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual System.Guid ContentTypeDefinitionId { get; set; }

    }

    public partial class ContentTypeRecordUpdateDto
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual System.Guid ContentTypeDefinitionId { get; set; }

    }

    public partial class ContentTypeRecordGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class ContentTypeRecordWithDetailsDto : ContentTypeRecordDto
    {
        public List<ContentPartRecordDto> ContentPartRecords { get; set; }

    }
}
