//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKitManagement.ContentRecords.Dtos
{

    public partial class ContentPartFieldRecordDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual System.Guid? TenantId { get; set; }

        public virtual string Name { get; set; }

        public virtual string Value { get; set; }

        public virtual System.Guid ContentPartRecordId { get; set; }

    }

    public partial class ContentPartFieldRecordCreateDto
    {
        public virtual System.Guid? TenantId { get; set; }

        public virtual string Name { get; set; }

        public virtual string Value { get; set; }

        public virtual System.Guid ContentPartRecordId { get; set; }

    }

    public partial class ContentPartFieldRecordUpdateDto
    {
        public virtual System.Guid? TenantId { get; set; }

        public virtual string Name { get; set; }

        public virtual string Value { get; set; }

        public virtual System.Guid ContentPartRecordId { get; set; }

    }

    public partial class ContentPartFieldRecordGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class ContentPartFieldRecordWithDetailsDto : ContentPartFieldRecordDto
    {
    }
}
