//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using FluentValidation;

namespace FS.CmsKitManagement.ContentRecords.Dtos
{
    public partial class ContentPartRecordCreateDtoValidator : AbstractValidator<ContentPartRecordCreateDto>
    {
        public ContentPartRecordCreateDtoValidator()
        {
            RuleFor(p => p.ContentPartDefinitionId)
                .NotNull()
                ;
            RuleFor(p => p.TenantId)
                ;
            RuleFor(p => p.ContentTypeRecordId)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
    public partial class ContentPartRecordUpdateDtoValidator : AbstractValidator<ContentPartRecordUpdateDto>
    {
        public ContentPartRecordUpdateDtoValidator()
        {
            RuleFor(p => p.ContentPartDefinitionId)
                .NotNull()
                ;
            RuleFor(p => p.TenantId)
                ;
            RuleFor(p => p.ContentTypeRecordId)
                .NotNull()
                ;
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }
}
