//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.ContentRecords
{
    public partial class ContentPartFieldRecordCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.CmsKitManagement.ContentRecords.ContentPartFieldRecord, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartFieldRecordWithDetailsDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartFieldRecordDto, 
            Guid, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartFieldRecordGetListDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartFieldRecordCreateDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartFieldRecordUpdateDto>,
        IContentPartFieldRecordCrudAppService
    {
        private readonly IContentPartFieldRecordRepository _repository;

        public ContentPartFieldRecordCrudAppService(IContentPartFieldRecordRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
