//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.ContentRecords
{
    public partial class ContentPartRecordCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.CmsKitManagement.ContentRecords.ContentPartRecord, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartRecordWithDetailsDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartRecordDto, 
            Guid, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartRecordGetListDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartRecordCreateDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentPartRecordUpdateDto>,
        IContentPartRecordCrudAppService
    {
        private readonly IContentPartRecordRepository _repository;

        public ContentPartRecordCrudAppService(IContentPartRecordRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
