//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKitManagement.ContentRecords
{
    public partial class ContentTypeRecordCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.CmsKitManagement.ContentRecords.ContentTypeRecord, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentTypeRecordWithDetailsDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentTypeRecordDto, 
            Guid, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentTypeRecordGetListDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentTypeRecordCreateDto, 
            FS.CmsKitManagement.ContentRecords.Dtos.ContentTypeRecordUpdateDto>,
        IContentTypeRecordCrudAppService
    {
        private readonly IContentTypeRecordRepository _repository;

        public ContentTypeRecordCrudAppService(IContentTypeRecordRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
