//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Abp.Emailing
{
    public partial interface IMailMessageTemplateCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.Abp.Emailing.Dtos.MailMessageTemplateWithDetailsDto, 
            FS.Abp.Emailing.Dtos.MailMessageTemplateDto, 
            Guid, 
            FS.Abp.Emailing.Dtos.MailMessageTemplateGetListDto, 
            FS.Abp.Emailing.Dtos.MailMessageTemplateCreateDto, 
            FS.Abp.Emailing.Dtos.MailMessageTemplateUpdateDto>
    {

    }
}
