//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.CmsKitManagement.Attachments.Dtos
{

    public partial class AttachmentDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual List<string> MediaDescriptorIds { get; set; }

    }

    public partial class AttachmentCreateDto
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual List<string> MediaDescriptorIds { get; set; }

    }

    public partial class AttachmentUpdateDto
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual List<string> MediaDescriptorIds { get; set; }

    }

    public partial class AttachmentGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class AttachmentWithDetailsDto : AttachmentDto
    {
    }
}
