//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKit.EntityMedias
{
    public partial interface IEntityMediaCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.CmsKit.EntityMedias.Dtos.EntityMediaWithDetailsDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaDto, 
            Guid, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGetListDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaCreateDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaUpdateDto>
    {

    }
}
