//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.CmsKit.EntityMedias
{
    public partial interface IEntityMediaGroupCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGroupWithDetailsDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGroupDto, 
            Guid, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGroupGetListDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGroupCreateDto, 
            FS.CmsKit.EntityMedias.Dtos.EntityMediaGroupUpdateDto>
    {

    }
}
