//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.Entity.EntityDefaults.Permissions
{
    public class EntityDefaultsPermissionNames
    {
        public const string ModuleName = "FS.Entity.EntityDefaults";
        public static class EntityDefault
        {
            public const string Default = ModuleName + ".EntityDefault";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class EntityDefaultItem
        {
            public const string Default = ModuleName + ".EntityDefaultItem";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(EntityDefaultsPermissionNames));
        }
    }
}
