//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;
namespace FS.FormManagement.EntityFrameworkCore
{
    public static partial class FormManagementDbContextModelCreatingExtensions
    {
        public static void ConfigureFormManagement(
            this ModelBuilder builder,
            Action<FormManagementModelBuilderConfigurationOptions> optionsAction = null)
        {
            Check.NotNull(builder, nameof(builder));

            var options = new FormManagementModelBuilderConfigurationOptions(
                FormManagementDbProperties.DbTablePrefix,
                FormManagementDbProperties.DbSchema
            );

            optionsAction?.Invoke(options);

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.FormManagement.EntityForms.EntityForm>(new FS.FormManagement.EntityForms.EntityFrameworkCore.EntityFormConfiguration(options.TablePrefix,options.Schema));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
