//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System.Reflection;
using AutoMapper;
using Volo.Abp.AutoMapper;

namespace FS.CmsKitManagement.Attachments.Dtos
{
    public partial class AttachmentAutoMapperProfile : Profile
    {
        public AttachmentAutoMapperProfile()
        {
            CreateMap<FS.CmsKitManagement.Attachments.Attachment, AttachmentDto>()
            .ReverseMap();
        
            CreateMap<AttachmentCreateDto, FS.CmsKitManagement.Attachments.Attachment>();
        
            CreateMap<AttachmentUpdateDto, FS.CmsKitManagement.Attachments.Attachment>();
        
            CreateMap<FS.CmsKitManagement.Attachments.Attachment, AttachmentWithDetailsDto>();
        
            CustomizeConfiguration();
        }
        partial void CustomizeConfiguration();
    }

}
