//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.Entity.MultiLinguals
{
    public partial interface IMultiLingualTranslationCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<
            FS.Entity.MultiLinguals.Dtos.MultiLingualTranslationWithDetailsDto, 
            FS.Entity.MultiLinguals.Dtos.MultiLingualTranslationDto, 
            Guid, 
            FS.Entity.MultiLinguals.Dtos.MultiLingualTranslationGetListDto, 
            FS.Entity.MultiLinguals.Dtos.MultiLingualTranslationCreateDto, 
            FS.Entity.MultiLinguals.Dtos.MultiLingualTranslationUpdateDto>
    {

    }
}
