//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.Social.Localization;
using FS.Social.Permissions;

namespace FS.Social.Codes.Permissions
{
    public partial class CodesPermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var group = context.GetGroup(SocialPermissions.GroupName);

            var Code = group.AddPermission(CodesPermissionNames.Code.Default,L(CodesPermissionNames.Code.Default));
            Code.AddChild(CodesPermissionNames.Code.Create , L("DisplayName:Code.Create"));
            Code.AddChild(CodesPermissionNames.Code.Update , L("DisplayName:Code.Update"));
            Code.AddChild(CodesPermissionNames.Code.Delete , L("DisplayName:Code.Delete"));

            CustomizeDefine(context);
        }

        partial void CustomizeDefine(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context);

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<SocialResource>(name);
        }
    }
}
