//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;

namespace FS.Abp.Emailing.EntityFrameworkCore
{
    public static partial class EmailingDbContextModelCreatingExtensions
    {
        public static void ConfigureEmailing(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.Abp.Emailing.MailMessageTemplate>(new FS.Abp.Emailing.EntityFrameworkCore.MailMessageTemplateConfiguration(AbpDbProperties.DbTablePrefix,AbpDbProperties.DbSchema));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
