//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using the template for generating Repositories and a Unit of Work for EF Core model.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace FS.CmsKit.ContentDefinitions
{
    public partial interface IContentTypePartDefinitionRepository : 
        Volo.Abp.Domain.Repositories.IRepository<FS.CmsKit.ContentDefinitions.ContentTypePartDefinition,Guid>
    {

    }
}
