//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using Volo.Abp.Application.Dtos;

namespace FS.FormManagement.EntityForms.Dtos
{

    public partial class EntityFormDto : Volo.Abp.Application.Dtos.ExtensibleAuditedEntityDto<Guid>
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual System.Guid FormId { get; set; }

    }

    public partial class EntityFormCreateDto
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual System.Guid FormId { get; set; }

    }

    public partial class EntityFormUpdateDto
    {
        public virtual string EntityType { get; set; }

        public virtual string EntityId { get; set; }

        public virtual System.Guid FormId { get; set; }

    }

    public partial class EntityFormGetListDto : PagedAndSortedResultRequestDto
    {
    }

    public partial class EntityFormWithDetailsDto : EntityFormDto
    {
    }
}
