//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.CmsKitManagement.ContentRecords.Permissions
{
    public class ContentRecordsPermissionNames
    {
        public const string ModuleName = "FS.CmsKitManagement.ContentRecords";
        public static class ContentTypeRecord
        {
            public const string Default = ModuleName + ".ContentTypeRecord";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ContentPartFieldRecord
        {
            public const string Default = ModuleName + ".ContentPartFieldRecord";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static class ContentPartRecord
        {
            public const string Default = ModuleName + ".ContentPartRecord";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(ContentRecordsPermissionNames));
        }
    }
}
