//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKit.ContentDefinitions
{
    public partial class ContentPartDefinitionCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.CmsKit.ContentDefinitions.ContentPartDefinition, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentPartDefinitionWithDetailsDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentPartDefinitionDto, 
            Guid, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentPartDefinitionGetListDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentPartDefinitionCreateDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentPartDefinitionUpdateDto>,
        IContentPartDefinitionCrudAppService
    {
        private readonly IContentPartDefinitionRepository _repository;

        public ContentPartDefinitionCrudAppService(IContentPartDefinitionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
