//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKit.ContentDefinitions
{
    public partial class ContentPartFieldDefinitionCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.CmsKit.ContentDefinitions.ContentPartFieldDefinition, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentPartFieldDefinitionWithDetailsDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentPartFieldDefinitionDto, 
            Guid, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentPartFieldDefinitionGetListDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentPartFieldDefinitionCreateDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentPartFieldDefinitionUpdateDto>,
        IContentPartFieldDefinitionCrudAppService
    {
        private readonly IContentPartFieldDefinitionRepository _repository;

        public ContentPartFieldDefinitionCrudAppService(IContentPartFieldDefinitionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
