//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKit.ContentDefinitions
{
    public partial class ContentTypePartDefinitionCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.CmsKit.ContentDefinitions.ContentTypePartDefinition, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentTypePartDefinitionWithDetailsDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentTypePartDefinitionDto, 
            Guid, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentTypePartDefinitionGetListDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentTypePartDefinitionCreateDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentTypePartDefinitionUpdateDto>,
        IContentTypePartDefinitionCrudAppService
    {
        private readonly IContentTypePartDefinitionRepository _repository;

        public ContentTypePartDefinitionCrudAppService(IContentTypePartDefinitionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
