//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

namespace FS.CmsKit.ContentDefinitions
{
    public partial class ContentTypeDefinitionCrudAppService :  // auto-generated
        Volo.Abp.Application.Services.CrudAppService<
            FS.CmsKit.ContentDefinitions.ContentTypeDefinition, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentTypeDefinitionWithDetailsDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentTypeDefinitionDto, 
            Guid, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentTypeDefinitionGetListDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentTypeDefinitionCreateDto, 
            FS.CmsKit.ContentDefinitions.Dtos.ContentTypeDefinitionUpdateDto>,
        IContentTypeDefinitionCrudAppService
    {
        private readonly IContentTypeDefinitionRepository _repository;

        public ContentTypeDefinitionCrudAppService(IContentTypeDefinitionRepository repository) : base(repository)
        {
            this._repository = repository;
        }
    }
}
