//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Reflection;

namespace FS.FormManagement.EntityForms
{
    public class EntityFormsPermissionNames
    {
        public const string ModuleName = "FS.FormManagement.EntityForms";
        public static class EntityForm
        {
            public const string Default = ModuleName + ".EntityForm";
            public const string Create = Default + ".Create";
            public const string Update = Default + ".Update";
            public const string Delete = Default + ".Delete";
        }
        public static string[] GetAll()
        {
            return ReflectionHelper.GetPublicConstantsRecursively(typeof(EntityFormsPermissionNames));
        }
    }
}
