//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using Volo.Abp.Localization;
using FS.FormManagement.Localization;

namespace FS.FormManagement.EntityForms
{
    public class EntityFormsPermissionDefinitionProvider : Volo.Abp.Authorization.Permissions.PermissionDefinitionProvider
    {
        public override void Define(Volo.Abp.Authorization.Permissions.IPermissionDefinitionContext context)
        {
            var _EntityFormsGroup = context.AddGroup(EntityFormsPermissionNames.ModuleName,L(EntityFormsPermissionNames.ModuleName));

            var EntityForm = _EntityFormsGroup.AddPermission(EntityFormsPermissionNames.EntityForm.Default,L(EntityFormsPermissionNames.EntityForm.Default));
            EntityForm.AddChild(EntityFormsPermissionNames.EntityForm.Create , L("DisplayName:EntityForm.Create"));
            EntityForm.AddChild(EntityFormsPermissionNames.EntityForm.Update , L("DisplayName:EntityForm.Update"));
            EntityForm.AddChild(EntityFormsPermissionNames.EntityForm.Delete , L("DisplayName:EntityForm.Delete"));

        }

        private static LocalizableString L(string name)
        {
            return LocalizableString.Create<FormManagementResource>(name);
        }
    }
}
