//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by YinChang.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Volo.Abp.Application.Services;

namespace FS.FormManagement.EntityForms
{
    public partial interface IEntityFormCrudAppService : // auto-generated
        Volo.Abp.Application.Services.ICrudAppService<FS.FormManagement.EntityForms.Dtos.EntityFormWithDetailsDto, Guid, FS.FormManagement.EntityForms.Dtos.EntityFormGetListDto, FS.FormManagement.EntityForms.Dtos.EntityFormCreateDto, FS.FormManagement.EntityForms.Dtos.EntityFormUpdateDto>
    {

    }
}
