
name: "build"

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: 6.0.300
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        persist-credentials: false
        token: ${{ secrets.Admin_Token || github.token }}

    - name: build all
      id: buildAction
      shell: pwsh
      working-directory: ./ci
      run: |
        ./build-all.ps1
      continue-on-error: true

    - name: read directoryBuild 
      id: directoryBuildProps 
      uses: juliangruber/read-file-action@v1
      with:
        path: ./Directory.Build.props

    - name: get version
      id: getVersion
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '(?<=>)[^<>]+(?=</Version>)'
        regex_flags: 'gim'
        search_string: '${{ steps.directoryBuildProps.outputs.content }}'
    
    - name: NotifyMessage while error
      uses: louis70109/line-notify-action@master
      if : steps.buildAction.outcome != 'success'
      with:
        token: ${{ secrets.LINE_NOTIFY_TOKEN }}
        message: 'Github get an error while build'