
name: "build"
#only build develop branches
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: 6.0.300
    - name: build all
      id: buildAction
      if: contains(matrix.os, 'windows-latest')
      run: .\build-all.ps1
      working-directory: .\ci
      shell: powershell
      continue-on-error: true

    - name: read directoryBuild 
      if: contains(matrix.os, 'windows-latest')
      id: directoryBuildProps 
      uses: juliangruber/read-file-action@v1
      with:
        path: ./Directory.Build.props

    - name: get version
      if: contains(matrix.os, 'windows-latest')
      id: getVersion
      uses: AsasInnab/regex-action@v1
      with:
        regex_pattern: '(?<=>)[^<>]+(?=</Version>)'
        regex_flags: 'gim'
        search_string: '${{ steps.directoryBuildProps.outputs.content }}'
    
    - name: NotifyMessage while error
      uses: louis70109/line-notify-action@master
      if : steps.buildAction.outcome != 'success' && contains(matrix.os, 'ubuntu-latest')
      with:
        token: ${{ secrets.LINE_NOTIFY_TOKEN }}
        message: 'Github get an error while build'