//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 5.1.3
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Microsoft.EntityFrameworkCore;
using Volo.Abp;

namespace FS.Entity.MultiLinguals.EntityFrameworkCore
{
    public static partial class MultiLingualsDbContextModelCreatingExtensions
    {
        public static void ConfigureMultiLinguals(
            this ModelBuilder builder)
        {
            Check.NotNull(builder, nameof(builder));

            CustomizeMapping(ref builder);

            builder.ApplyConfiguration<FS.Entity.MultiLinguals.MultiLingualTranslation>(new FS.Entity.MultiLinguals.EntityFrameworkCore.MultiLingualTranslationConfiguration(EntityDbProperties.DbTablePrefix,EntityDbProperties.DbSchema));
            builder.ApplyConfiguration<FS.Entity.MultiLinguals.MultiLingual>(new FS.Entity.MultiLinguals.EntityFrameworkCore.MultiLingualConfiguration(EntityDbProperties.DbTablePrefix,EntityDbProperties.DbSchema));
        }
        static partial void CustomizeMapping(ref ModelBuilder modelBuilder);
    }
}
