//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// 4.4.4
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Volo.Abp.EntityFrameworkCore.Modeling;

namespace FS.Social.Codes.EntityFrameworkCore
{
    public partial class CodeConfiguration : IEntityTypeConfiguration<Code> //auto-generated
    {
        private string tablePrefix;
        private string schema;
        public CodeConfiguration(string tablePrefix, string schema)
        {
            this.tablePrefix = tablePrefix;
            this.schema = schema;
        }
        public void Configure(EntityTypeBuilder<Code> builder)
        {
            builder.ToTable(tablePrefix + @"Codes", schema);
            builder.Property<Guid>(@"Id").HasColumnName(@"Id").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Value).HasColumnName(@"Value").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.ProviderName).HasColumnName(@"ProviderName").ValueGeneratedNever();
            builder.Property(x => x.ProviderKey).HasColumnName(@"ProviderKey").ValueGeneratedNever();
            builder.HasKey(@"Id");

            builder.ConfigureAuditedAggregateRoot();
            builder.HasIndex(x => x.CreationTime);

            CustomizeConfiguration(builder);
        }

        partial void CustomizeConfiguration(EntityTypeBuilder<Code> builder);
    }
    public static partial class CodeQueryableExtensions //auto-generated
    {
    }
}
